"""Pynecil - Python library to communicate with Pinecil V2 soldering irons via Bluetooth."""

__version__ = "4.3.1"
from .client import Pynecil, discover
from .exceptions import CommunicationError, UpdateException
from .types import (
    AccelerometerValues,
    AnimationSpeed,
    AutostartMode,
    BatteryType,
    CharBulk,
    CharGameJam,
    CharLive,
    CharSetting,
    DeviceInfoResponse,
    LanguageCode,
    LiveDataResponse,
    LockingMode,
    LogoDuration,
    OperatingMode,
    PinecilMenus,
    PowerSource,
    ScreenOrientationMode,
    ScrollSpeed,
    SettingsDataResponse,
    TempUnit,
    TipType,
    USBPDMode,
)
from .update import IronOSUpdate, LatestRelease

__all__ = [
    "AccelerometerValues",
    "AnimationSpeed",
    "AutostartMode",
    "BatteryType",
    "CharBulk",
    "CharGameJam",
    "CharLive",
    "CharSetting",
    "CommunicationError",
    "DeviceInfoResponse",
    "discover",
    "IronOSUpdate",
    "LanguageCode",
    "LatestRelease",
    "LiveDataResponse",
    "LockingMode",
    "LogoDuration",
    "OperatingMode",
    "PinecilMenus",
    "PowerSource",
    "Pynecil",
    "ScreenOrientationMode",
    "ScrollSpeed",
    "SettingsDataResponse",
    "TempUnit",
    "TipType",
    "UpdateException",
    "USBPDMode",
]
